--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.2.280.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 09/12/2014 11:57:37
-- Server version: 5.5.5-10.0.15-MariaDB
-- Client version: 4.1
--


-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set default database
--
USE jweb;

--
-- Definition for table category
--
DROP TABLE IF EXISTS category;
CREATE TABLE category (
  ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  description TEXT DEFAULT NULL,
  creationDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updateDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table user
--
DROP TABLE IF EXISTS user;
CREATE TABLE user (
  ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(512) NOT NULL,
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  role ENUM('U','A') NOT NULL DEFAULT 'U',
  mail VARCHAR(255) NOT NULL,
  creationDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table `order`
--
DROP TABLE IF EXISTS `order`;
CREATE TABLE `order` (
  ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  userID INT(10) UNSIGNED NOT NULL,
  status ENUM('P','W','D','C') NOT NULL DEFAULT 'P',
  promotion INT(11) UNSIGNED DEFAULT NULL,
  createdDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  CONSTRAINT FK_order_user_ID FOREIGN KEY (userID)
    REFERENCES user(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table abonewsletter
--
DROP TABLE IF EXISTS abonewsletter;
CREATE TABLE abonewsletter (
  ID INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  mail VARCHAR(255) NOT NULL,
  firstName VARCHAR(255) DEFAULT NULL,
  lastName VARCHAR(255) DEFAULT NULL,
  fk_userID INT(10) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_AboNewsletter_user_ID FOREIGN KEY (fk_userID)
    REFERENCES user(ID) ON DELETE SET NULL ON UPDATE SET NULL
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table news
--
DROP TABLE IF EXISTS news;
CREATE TABLE news (
  ID INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  createdBy INT(10) UNSIGNED DEFAULT NULL,
  createdDate DATETIME NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_news_user_ID FOREIGN KEY (createdBy)
    REFERENCES user(ID) ON DELETE SET NULL ON UPDATE SET NULL
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table product
--
DROP TABLE IF EXISTS product;
CREATE TABLE product (
  ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  description TEXT DEFAULT NULL,
  category INT(11) UNSIGNED DEFAULT NULL,
  price DECIMAL(19, 2) NOT NULL,
  quantity SMALLINT(6) NOT NULL,
  createdBy INT(10) UNSIGNED DEFAULT NULL,
  creationDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updateDate DATETIME NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_product_category_ID FOREIGN KEY (category)
    REFERENCES category(ID) ON DELETE SET NULL ON UPDATE SET NULL,
  CONSTRAINT FK_product_user_ID FOREIGN KEY (createdBy)
    REFERENCES user(ID) ON DELETE SET NULL ON UPDATE SET NULL
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table cartitem
--
DROP TABLE IF EXISTS cartitem;
CREATE TABLE cartitem (
  ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  orderID INT(10) UNSIGNED NOT NULL,
  productID INT(10) UNSIGNED NOT NULL,
  addDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  CONSTRAINT FK_cartitem_order_ID FOREIGN KEY (orderID)
    REFERENCES `order`(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_cartitem_product_ID FOREIGN KEY (productID)
    REFERENCES product(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

-- 
-- Dumping data for table category
--

-- Table jweb.category does not contain any data (it is empty)

-- 
-- Dumping data for table user
--

-- Table jweb.user does not contain any data (it is empty)

-- 
-- Dumping data for table `order`
--

-- Table jweb.`order` does not contain any data (it is empty)

-- 
-- Dumping data for table abonewsletter
--

-- Table jweb.abonewsletter does not contain any data (it is empty)

-- 
-- Dumping data for table news
--

-- Table jweb.news does not contain any data (it is empty)

-- 
-- Dumping data for table product
--

-- Table jweb.product does not contain any data (it is empty)

-- 
-- Dumping data for table cartitem
--

-- Table jweb.cartitem does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;